### PR TITLE
added custom404 page in admin #83

### PR DESCRIPTION
**Pull request by pavithrakumar22**
this is the same replica of the custom404 page created in alpha_frontend
admin_login
admin_in

### CODE REVIEW

**Review by Divesh-singh — COMMENTED** [review]
Update PR Title to have ticket number associated with task

**Comment by pavithrakumar22** [comment]
> Update PR Title to have ticket number associated with task

now is it ok?

**Comment by Divesh-singh** [comment]
> > Update PR Title to have ticket number associated with task
> 
> now is it ok?

not this, you should have been assigned a notion ticket, add the notion ticket number in front of PR

Expected PR title format is as follows
PR title format => <ticket number>: <Brief title explaining bug or feature that is to be merged in PR>
Eg => SP3-89: Added copy button and redirect in business project

**Comment by pavithrakumar22** [comment]
> > > Update PR Title to have ticket number associated with task
> > 
> > 
> > now is it ok?
> 
> not this, you should have been assigned a notion ticket, add the notion ticket number in front of PR
> 
> Expected PR title format is as follows PR title format => : Eg => SP3-89: Added copy button and redirect in business project
>>
>sir we have not been given access to notion so for now we are uploading the pr in the above format

**Pull request merged**
